name: ua-geotransformer-repro
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - xgboost
  - shap
  - scipy
  - rasterio
  - pyyaml
  - tqdm
  - pip
  - pip:
      - torch