paths:
  raw_dir: data/raw
  processed_dir: data/processed
  outputs_dir: outputs
  study_area: data/raw/study_area.shp
  drivers_stack: data/raw/all_drivers.tif
  landuse_2010: data/raw/2010_9.tif
  landuse_2017: data/raw/2017_9.tif

params:
  random_seed: 42
  test_size: 0.2
  model_type: xgboost  # or 'geotransformer' when scripted

geotransformer:
  enabled: false
  # add model hyperparameters here